apiVersion: v1
kind: Pod
metadata:
  name: hello-docker
  labels:
    app: hello-docker
spec:
  containers:
    - name: hello-docker
      image: index.docker.io/koukidan/hello-docker
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: hello-docker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: hello-docker-service
    servicePort: 80

